{
  "schema": 1,
  "source": {
    "profile": "arch",
    "snapshot": "2026-10-07"
  },
  "system": {
    "hostname": "looom-limine",
    "timezone": "Europe/Moscow",
    "locale": "en_US.UTF-8",
    "console_keymap": "us"
  },
  "kernel": {
    "package": "linux",
    "extra_command_line": []
  },
  "desktop": {
    "environment": "plasma",
    "sessions": [
      "niri"
    ]
  },
  "packages": [
    "intel-ucode",
    "amd-ucode"
  ],
  "accounts": {
    "user": {
      "name": "kexfff",
      "uid": 1000,
      "gid": 1000,
      "groups": [
        "wheel"
      ],
      "shell": "/bin/bash",
      "password_secret": "login-kexfff"
    },
    "root": {
      "password_secret": "login-root"
    }
  },
  "units": {
    "sshd.service": "enabled"
  },
  "files": {},
  "persistent": {
    "directories": {
      "/etc/NetworkManager/system-connections": {
        "id": "network-connections",
        "owner": "root",
        "group": "root",
        "mode": "0700"
      },
      "/etc/looom-local": {
        "id": "local-settings",
        "owner": "root",
        "group": "root",
        "mode": "0700"
      }
    }
  },
  "health": {
    "required_units": [
      "sshd.service"
    ]
  },
  "packages_from": [
    "container-packages.yaml"
  ]
}
